// Code generated by protoc-gen-echo-v5. DO NOT EDIT.
// source: helloworld/v1/helloworld.proto

package helloworldv1echo

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/ca-x/bufplugins/examples/echo-v5/api/helloworld/v1"
	helloworldv1connect "github.com/ca-x/bufplugins/examples/echo-v5/api/helloworld/v1/helloworldv1connect"
	echoadapter "github.com/ca-x/bufplugins/runtime/echoadapter"
	httpadapter "github.com/ca-x/bufplugins/runtime/httpadapter"
	v5 "github.com/labstack/echo/v5"
	proto "google.golang.org/protobuf/proto"
)

type GreeterServiceEchoRegistrar struct {
	Service helloworldv1connect.GreeterServiceHandler
	Options []echoadapter.Option
}

func NewGreeterServiceEchoRegistrar(svc helloworldv1connect.GreeterServiceHandler, opts ...echoadapter.Option) GreeterServiceEchoRegistrar {
	return GreeterServiceEchoRegistrar{Service: svc, Options: opts}
}

func RegisterGreeterServiceToEcho(e *v5.Echo, svc helloworldv1connect.GreeterServiceHandler, opts ...echoadapter.Option) error {
	return NewGreeterServiceEchoRegistrar(svc, opts...).Register(e)
}

func (r GreeterServiceEchoRegistrar) Register(e *v5.Echo) error {
	cfg := echoadapter.NewConfig(r.Options...)
	connectPath, connectHandler := helloworldv1connect.NewGreeterServiceHandler(r.Service, cfg.ConnectOptions...)
	spec := greeterServiceEchoSpec(r.Service)
	spec.ConnectPath = connectPath
	return (echoadapter.ServiceRegistrar{Spec: spec, ConnectHandler: connectHandler, Config: cfg}).Register(e)
}

func greeterServiceEchoSpec(svc helloworldv1connect.GreeterServiceHandler) httpadapter.ServiceSpec {
	return httpadapter.ServiceSpec{
		Name:   "helloworld.v1.GreeterService",
		GoName: "GreeterService",
		Methods: []httpadapter.MethodSpec{
			{
				ServiceName:     "helloworld.v1.GreeterService",
				ServiceGoName:   "GreeterService",
				Name:            "SayHello",
				GoName:          "SayHello",
				Procedure:       helloworldv1connect.GreeterServiceSayHelloProcedure,
				RequestFactory:  func() proto.Message { return new(v1.SayHelloRequest) },
				ResponseFactory: func() proto.Message { return new(v1.SayHelloResponse) },
				ClientStreaming: false,
				ServerStreaming: false,
				UnaryInvoker: func(ctx context.Context, msg proto.Message) (proto.Message, error) {
					resp, err := svc.SayHello(ctx, connect.NewRequest(msg.(*v1.SayHelloRequest)))
					if resp == nil {
						return nil, err
					}
					return resp.Msg, err
				},
				HTTPBindings: []httpadapter.HTTPBinding{
					{
						Method:       "GET",
						Path:         "/helloworld/:name",
						Body:         "",
						ResponseBody: "",
						PathParams: []httpadapter.PathParam{
							{
								Name:  "name",
								Field: "name",
							},
						},
					},
				},
			},
			{
				ServiceName:     "helloworld.v1.GreeterService",
				ServiceGoName:   "GreeterService",
				Name:            "LuckySearch",
				GoName:          "LuckySearch",
				Procedure:       helloworldv1connect.GreeterServiceLuckySearchProcedure,
				RequestFactory:  func() proto.Message { return new(v1.LuckySearchRequest) },
				ResponseFactory: func() proto.Message { return new(v1.LuckySearchResponse) },
				ClientStreaming: false,
				ServerStreaming: false,
				UnaryInvoker: func(ctx context.Context, msg proto.Message) (proto.Message, error) {
					resp, err := svc.LuckySearch(ctx, connect.NewRequest(msg.(*v1.LuckySearchRequest)))
					if resp == nil {
						return nil, err
					}
					return resp.Msg, err
				},
				HTTPBindings: []httpadapter.HTTPBinding{
					{
						Method:       "GET",
						Path:         "/search/:keyword",
						Body:         "",
						ResponseBody: "",
						PathParams: []httpadapter.PathParam{
							{
								Name:  "keyword",
								Field: "keyword",
							},
						},
					},
				},
			},
			{
				ServiceName:     "helloworld.v1.GreeterService",
				ServiceGoName:   "GreeterService",
				Name:            "CreateGreeting",
				GoName:          "CreateGreeting",
				Procedure:       helloworldv1connect.GreeterServiceCreateGreetingProcedure,
				RequestFactory:  func() proto.Message { return new(v1.CreateGreetingRequest) },
				ResponseFactory: func() proto.Message { return new(v1.CreateGreetingResponse) },
				ClientStreaming: false,
				ServerStreaming: false,
				UnaryInvoker: func(ctx context.Context, msg proto.Message) (proto.Message, error) {
					resp, err := svc.CreateGreeting(ctx, connect.NewRequest(msg.(*v1.CreateGreetingRequest)))
					if resp == nil {
						return nil, err
					}
					return resp.Msg, err
				},
				HTTPBindings: []httpadapter.HTTPBinding{
					{
						Method:       "POST",
						Path:         "/greetings",
						Body:         "*",
						ResponseBody: "message",
					},
				},
			},
		},
	}
}

const (
	GreeterServiceSayHelloMethodKey       = "GreeterService.SayHello"
	GreeterServiceLuckySearchMethodKey    = "GreeterService.LuckySearch"
	GreeterServiceCreateGreetingMethodKey = "GreeterService.CreateGreeting"
)
