// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: helloworld/v1/helloworld.proto

package helloworldv1

import (
	_ "buf.build/go/protovalidate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LuckySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckySearchRequest) Reset() {
	*x = LuckySearchRequest{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckySearchRequest) ProtoMessage() {}

func (x *LuckySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckySearchRequest.ProtoReflect.Descriptor instead.
func (*LuckySearchRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *LuckySearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *LuckySearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LuckySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckySearchResponse) Reset() {
	*x = LuckySearchResponse{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckySearchResponse) ProtoMessage() {}

func (x *LuckySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckySearchResponse.ProtoReflect.Descriptor instead.
func (*LuckySearchResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *LuckySearchResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateGreetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGreetingRequest) Reset() {
	*x = CreateGreetingRequest{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreetingRequest) ProtoMessage() {}

func (x *CreateGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreetingRequest.ProtoReflect.Descriptor instead.
func (*CreateGreetingRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGreetingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateGreetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGreetingResponse) Reset() {
	*x = CreateGreetingResponse{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreetingResponse) ProtoMessage() {}

func (x *CreateGreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreetingResponse.ProtoReflect.Descriptor instead.
func (*CreateGreetingResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGreetingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGreetingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworld_v1_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_v1_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x1ehelloworld/v1/helloworld.proto\x12\rhelloworld.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x0fSayHelloRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@R\x04name\"5\n" +
	"\x10SayHelloResponse\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\"[\n" +
	"\x12LuckySearchRequest\x12$\n" +
	"\akeyword\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\akeyword\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\n" +
	"(\x01R\x05limit\"9\n" +
	"\x13LuckySearchResponse\x12\"\n" +
	"\aresults\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\aresults\"\\\n" +
	"\x15CreateGreetingRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@R\x04name\x12$\n" +
	"\amessage\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\amessage\"T\n" +
	"\x16CreateGreetingResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage2\xe9\x02\n" +
	"\x0eGreeterService\x12g\n" +
	"\bSayHello\x12\x1e.helloworld.v1.SayHelloRequest\x1a\x1f.helloworld.v1.SayHelloResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/helloworld/{name}\x12o\n" +
	"\vLuckySearch\x12!.helloworld.v1.LuckySearchRequest\x1a\".helloworld.v1.LuckySearchResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/search/{keyword}\x12}\n" +
	"\x0eCreateGreeting\x12$.helloworld.v1.CreateGreetingRequest\x1a%.helloworld.v1.CreateGreetingResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*b\amessage\"\n" +
	"/greetingsB\xc5\x01\n" +
	"\x11com.helloworld.v1B\x0fHelloworldProtoP\x01ZJgithub.com/ca-x/bufplugins/examples/echo-v5/api/helloworld/v1;helloworldv1\xa2\x02\x03HXX\xaa\x02\rHelloworld.V1\xca\x02\rHelloworld\\V1\xe2\x02\x19Helloworld\\V1\\GPBMetadata\xea\x02\x0eHelloworld::V1b\x06proto3"

var (
	file_helloworld_v1_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_v1_helloworld_proto_rawDescData []byte
)

func file_helloworld_v1_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_v1_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_helloworld_proto_rawDesc), len(file_helloworld_v1_helloworld_proto_rawDesc)))
	})
	return file_helloworld_v1_helloworld_proto_rawDescData
}

var file_helloworld_v1_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_helloworld_v1_helloworld_proto_goTypes = []any{
	(*SayHelloRequest)(nil),        // 0: helloworld.v1.SayHelloRequest
	(*SayHelloResponse)(nil),       // 1: helloworld.v1.SayHelloResponse
	(*LuckySearchRequest)(nil),     // 2: helloworld.v1.LuckySearchRequest
	(*LuckySearchResponse)(nil),    // 3: helloworld.v1.LuckySearchResponse
	(*CreateGreetingRequest)(nil),  // 4: helloworld.v1.CreateGreetingRequest
	(*CreateGreetingResponse)(nil), // 5: helloworld.v1.CreateGreetingResponse
}
var file_helloworld_v1_helloworld_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.GreeterService.SayHello:input_type -> helloworld.v1.SayHelloRequest
	2, // 1: helloworld.v1.GreeterService.LuckySearch:input_type -> helloworld.v1.LuckySearchRequest
	4, // 2: helloworld.v1.GreeterService.CreateGreeting:input_type -> helloworld.v1.CreateGreetingRequest
	1, // 3: helloworld.v1.GreeterService.SayHello:output_type -> helloworld.v1.SayHelloResponse
	3, // 4: helloworld.v1.GreeterService.LuckySearch:output_type -> helloworld.v1.LuckySearchResponse
	5, // 5: helloworld.v1.GreeterService.CreateGreeting:output_type -> helloworld.v1.CreateGreetingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_helloworld_proto_init() }
func file_helloworld_v1_helloworld_proto_init() {
	if File_helloworld_v1_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_helloworld_proto_rawDesc), len(file_helloworld_v1_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_v1_helloworld_proto = out.File
	file_helloworld_v1_helloworld_proto_goTypes = nil
	file_helloworld_v1_helloworld_proto_depIdxs = nil
}
