package generator

import (
	"fmt"
	"path"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	contextImport     protogen.GoImportPath = "context"
	connectImport     protogen.GoImportPath = "connectrpc.com/connect"
	echoImport        protogen.GoImportPath = "github.com/labstack/echo/v5"
	httpAdapterImport protogen.GoImportPath = "github.com/ca-x/bufplugins/runtime/httpadapter"
	protoImport       protogen.GoImportPath = "google.golang.org/protobuf/proto"
)

func GenerateFile(plugin *protogen.Plugin, file *protogen.File, opts Options) error {
	if err := opts.Validate(); err != nil {
		return err
	}
	if len(file.Services) == 0 {
		return nil
	}
	echoPackageName := file.GoPackageName
	echoImportPath := file.GoImportPath
	filenamePrefix := file.GeneratedFilenamePrefix
	if opts.PackageSuffix != "" {
		echoPackageName += protogen.GoPackageName(opts.PackageSuffix)
		echoImportPath = protogen.GoImportPath(path.Join(string(file.GoImportPath), string(echoPackageName)))
		filenamePrefix = path.Join(path.Dir(filenamePrefix), string(echoPackageName), path.Base(filenamePrefix))
	}
	filename := filenamePrefix + opts.FileSuffix
	g := plugin.NewGeneratedFile(filename, echoImportPath)
	g.P("// Code generated by protoc-gen-echo-v5. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", echoPackageName)
	g.P()

	echoIdent := protogen.GoIdent{GoImportPath: echoImport, GoName: "Echo"}
	echoAdapterImport := protogen.GoImportPath(opts.RuntimeImport)
	echoOptionIdent := protogen.GoIdent{GoImportPath: echoAdapterImport, GoName: "Option"}
	echoConfigIdent := protogen.GoIdent{GoImportPath: echoAdapterImport, GoName: "NewConfig"}
	echoRegistrarIdent := protogen.GoIdent{GoImportPath: echoAdapterImport, GoName: "ServiceRegistrar"}

	for _, service := range file.Services {
		connectGenImport := connectImportPath(file, opts.ConnectPackageSuffix)
		if connectGenImport == echoImportPath && echoImportPath != file.GoImportPath {
			return fmt.Errorf("%s: echo package import path and connect package import path both resolve to %q", file.Desc.Path(), echoImportPath)
		}
		handlerIdent := protogen.GoIdent{GoImportPath: connectGenImport, GoName: service.GoName + "Handler"}
		newHandlerIdent := protogen.GoIdent{GoImportPath: connectGenImport, GoName: "New" + service.GoName + "Handler"}
		registrarName := service.GoName + "EchoRegistrar"
		constructorName := "New" + service.GoName + "EchoRegistrar"
		registerName := "Register" + service.GoName + "ToEcho"
		specFuncName := unexported(service.GoName) + "EchoSpec"

		g.P("type ", registrarName, " struct {")
		g.P("Service ", g.QualifiedGoIdent(handlerIdent))
		g.P("Options []", g.QualifiedGoIdent(echoOptionIdent))
		g.P("}")
		g.P()
		g.P("func ", constructorName, "(svc ", g.QualifiedGoIdent(handlerIdent), ", opts ...", g.QualifiedGoIdent(echoOptionIdent), ") ", registrarName, " {")
		g.P("return ", registrarName, "{Service: svc, Options: opts}")
		g.P("}")
		g.P()
		g.P("func ", registerName, "(e *", g.QualifiedGoIdent(echoIdent), ", svc ", g.QualifiedGoIdent(handlerIdent), ", opts ...", g.QualifiedGoIdent(echoOptionIdent), ") error {")
		g.P("return ", constructorName, "(svc, opts...).Register(e)")
		g.P("}")
		g.P()
		g.P("func (r ", registrarName, ") Register(e *", g.QualifiedGoIdent(echoIdent), ") error {")
		g.P("cfg := ", g.QualifiedGoIdent(echoConfigIdent), "(r.Options...)")
		g.P("connectPath, connectHandler := ", g.QualifiedGoIdent(newHandlerIdent), "(r.Service, cfg.ConnectOptions...)")
		g.P("spec := ", specFuncName, "(r.Service)")
		g.P("spec.ConnectPath = connectPath")
		g.P("return (", g.QualifiedGoIdent(echoRegistrarIdent), "{Spec: spec, ConnectHandler: connectHandler, Config: cfg}).Register(e)")
		g.P("}")
		g.P()
		if err := generateSpec(g, service, handlerIdent, specFuncName); err != nil {
			return err
		}
	}
	return nil
}

func generateSpec(g *protogen.GeneratedFile, service *protogen.Service, handlerIdent protogen.GoIdent, specFuncName string) error {
	serviceSpecIdent := protogen.GoIdent{GoImportPath: httpAdapterImport, GoName: "ServiceSpec"}
	methodSpecIdent := protogen.GoIdent{GoImportPath: httpAdapterImport, GoName: "MethodSpec"}
	bindingIdent := protogen.GoIdent{GoImportPath: httpAdapterImport, GoName: "HTTPBinding"}
	pathParamIdent := protogen.GoIdent{GoImportPath: httpAdapterImport, GoName: "PathParam"}
	contextIdent := protogen.GoIdent{GoImportPath: contextImport, GoName: "Context"}
	messageIdent := protogen.GoIdent{GoImportPath: protoImport, GoName: "Message"}

	g.P("func ", specFuncName, "(svc ", g.QualifiedGoIdent(handlerIdent), ") ", g.QualifiedGoIdent(serviceSpecIdent), " {")
	g.P("return ", g.QualifiedGoIdent(serviceSpecIdent), "{")
	g.P("Name: ", strconv.Quote(string(service.Desc.FullName())), ",")
	g.P("GoName: ", strconv.Quote(service.GoName), ",")
	g.P("Methods: []", g.QualifiedGoIdent(methodSpecIdent), "{")
	for _, method := range service.Methods {
		bindings, err := methodBindings(method)
		if err != nil {
			return err
		}
		if (method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer()) && len(bindings) > 0 {
			return fmt.Errorf("%s: google.api.http bindings for streaming RPCs are not supported", method.Desc.FullName())
		}
		g.P("{")
		g.P("ServiceName: ", strconv.Quote(string(service.Desc.FullName())), ",")
		g.P("ServiceGoName: ", strconv.Quote(service.GoName), ",")
		g.P("Name: ", strconv.Quote(string(method.Desc.Name())), ",")
		g.P("GoName: ", strconv.Quote(method.GoName), ",")
		g.P("Procedure: ", g.QualifiedGoIdent(procedureIdent(handlerIdent.GoImportPath, service, method)), ",")
		g.P("RequestFactory: func() ", g.QualifiedGoIdent(messageIdent), " { return new(", g.QualifiedGoIdent(method.Input.GoIdent), ") },")
		g.P("ResponseFactory: func() ", g.QualifiedGoIdent(messageIdent), " { return new(", g.QualifiedGoIdent(method.Output.GoIdent), ") },")
		g.P("ClientStreaming: ", method.Desc.IsStreamingClient(), ",")
		g.P("ServerStreaming: ", method.Desc.IsStreamingServer(), ",")
		if !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			g.P("UnaryInvoker: func(ctx ", g.QualifiedGoIdent(contextIdent), ", msg ", g.QualifiedGoIdent(messageIdent), ") (", g.QualifiedGoIdent(messageIdent), ", error) {")
			g.P("resp, err := svc.", method.GoName, "(ctx, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: connectImport, GoName: "NewRequest"}), "(msg.(*", g.QualifiedGoIdent(method.Input.GoIdent), ")))")
			g.P("if resp == nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("return resp.Msg, err")
			g.P("},")
		}
		if len(bindings) > 0 {
			g.P("HTTPBindings: []", g.QualifiedGoIdent(bindingIdent), "{")
			for _, binding := range bindings {
				g.P("{")
				g.P("Method: ", strconv.Quote(binding.Method), ",")
				g.P("Path: ", strconv.Quote(binding.Path), ",")
				g.P("Body: ", strconv.Quote(binding.Body), ",")
				g.P("ResponseBody: ", strconv.Quote(binding.ResponseBody), ",")
				if len(binding.PathParams) > 0 {
					g.P("PathParams: []", g.QualifiedGoIdent(pathParamIdent), "{")
					for _, param := range binding.PathParams {
						g.P("{")
						g.P("Name: ", strconv.Quote(param.Name), ",")
						g.P("Field: ", strconv.Quote(param.Field), ",")
						if param.Template != "" {
							g.P("Template: ", strconv.Quote(param.Template), ",")
						}
						if len(param.Names) > 0 {
							g.P("Names: []string{")
							for _, name := range param.Names {
								g.P(strconv.Quote(name), ",")
							}
							g.P("},")
						}
						g.P("},")
					}
					g.P("},")
				}
				g.P("},")
			}
			g.P("},")
		}
		g.P("},")
	}
	g.P("},")
	g.P("}")
	g.P("}")
	g.P()
	if len(service.Methods) > 0 {
		g.P("const (")
		for _, method := range service.Methods {
			g.P(methodKeyConstName(service, method), " = ", strconv.Quote(httpadapterMethodKey(service, method)))
		}
		g.P(")")
		g.P()
	}
	return nil
}

func connectImportPath(file *protogen.File, suffix string) protogen.GoImportPath {
	if suffix == "" {
		return file.GoImportPath
	}
	connectPackage := string(file.GoPackageName) + suffix
	return protogen.GoImportPath(path.Join(string(file.GoImportPath), connectPackage))
}

func procedureIdent(importPath protogen.GoImportPath, service *protogen.Service, method *protogen.Method) protogen.GoIdent {
	return protogen.GoIdent{
		GoImportPath: importPath,
		GoName:       service.GoName + method.GoName + "Procedure",
	}
}

func methodKeyConstName(service *protogen.Service, method *protogen.Method) string {
	return service.GoName + method.GoName + "MethodKey"
}

func httpadapterMethodKey(service *protogen.Service, method *protogen.Method) string {
	return service.GoName + "." + method.GoName
}

func unexported(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}
